import LanguageContext from "./LanguageContext"

export const metadata = {
  title: 'Hacker2Skill Chat',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
  <LanguageContext>
    <html lang="es">
      <body>{children}</body>
    </html>
  </LanguageContext>
  )
}
